### ISSUE TITLE
Flow editor not rendering

### ISSUE THREAD

**Issue by maciejmaksymo** [bichlepa/AutoHotFlow#1]
Hello,

Sadly the editor is not rendering for master branch.
It is working on the AutoHotFlow-1.0 branch.

I would use the AutoHotFlow-1.0 branch but it's missing the translation feature

![editor not rendering](https://user-images.githubusercontent.com/31704642/30125295-3e1a5d9a-9338-11e7-94c6-08d8c08019e2.png)

**Comment by maciejmaksymo** [comment]
Nevermind now I can see that the language settings were moved and the editor works in the AutoHotFlow-1.0 branch

**Comment by bichlepa** [comment]
Hello, the 1.0 branch is not completely implemented yet. Unfortunately I don't have much time for this project.

**Comment by maciejmaksymo** [comment]
Thank you for your great work. You created a gem here.

**Comment by bichlepa** [comment]
Thank you. For what purpose do you want to use it?

**Comment by maciejmaksymo** [comment]
I was looking for an open-source alternative to Blue Prism - Robotic Process Automation.
First I found AutoHotkey which in itself is a great way to automate a process. Sadly it lacked a GUI which would allow non-developer users (still IT but not software developers) to develop solutions. That is where your AutoHotFlow comes in.

**Comment by bichlepa** [comment]
Cool, I did not notice the software Blue Prism. Well,  it will take a while until AutoHotFlow will become an alternative for that. I hope I'll find some time in the next mouths to finish the first 1.0 release. Afterwards maybe some other people will start to contribute.
