### ISSUE TITLE
Elements API.odt - out of date?

### ISSUE THREAD

**Issue by burque505** [bichlepa/AutoHotFlow#2]
- Issue: Possible changes needed to "Elements Api Description" document.

- Description of problem:

At page 1, 2(d): 
`In function Element_getParameters_Action_Beep() delete the parameter names and replace them by these:
     return["frequency", "duration"]
`

No function Element_getParameters_Action_Beep() exists in the referenced New_Variable.ahk from which cloning is done.

**Comment by bichlepa** [comment]
Yes, it is outdated, sorry. I'm alrady working on an update of the documentation.

**Comment by burque505** [comment]
Thank you for the fast response, I know documentation is tough.

**Comment by bichlepa** [comment]
I just finished the documentation. I'm looking forward to see what you will implement! 
Be aware that the template in the element template creator is not updated yet.
