### ISSUE TITLE
Version 1.1.0 - cannot define working time out for Message box

### ISSUE THREAD

**Issue by burque505** [bichlepa/AutoHotFlow#5]
Issue: Message box only displays correctly if no timeout is set.
Steps to reproduce: 
1. Create 'Message box'
2. Define arbitrary timeout (anything but 'no timeout')
Result: Message box flickers and disappears
Last version with working timeout: Unknown

**Comment by bichlepa** [comment]
Thank you. I found the bug, "Input dialog" hat also the same bug. It will be fixed in the next release.

**Comment by burque505** [comment]
Thank you, and thank you for all your hard work on AutoHotFlow.

**Comment by burque505** [comment]
Closed, as bug has been found and will be fixed in next release.
