### ISSUE TITLE
Demonstation folder can be renamed

### ISSUE THREAD

**Issue by megabugman** [bichlepa/AutoHotFlow#6]
select name and press delete:
![02_Rename_via_Delete](https://user-images.githubusercontent.com/17204819/140590197-5f638014-f7b2-4167-8dfc-856f5ceccfd6.gif)

**Comment by bichlepa** [comment]
Thank you for reporting!
I fixed that. It also happened with the "uncategorized" folder.
The fix will be available in the next release.
